<?php

namespace App\DTO;

class VoucherItemData
{
    public function __construct(
        public int $VoucherItemID,
        public int $SLRef,
        public float $Debit,
        public float $Credit,
        public float $CurrencyAmount,
        public float $BaseCurrencyAmount,
        public float $CurrencyCredit,
        public float $CurrencyDebit,
        public int $CurrencyRef,
        public int $BaseCurrencyRef,
        public float $OperationalCurrencyExchangeRate,
        public int $OperationalCurrencyExchangeRateRef,
        public float $BaseCurrencyExchangeRate,
        public int $BaseCurrencyExchangeRateRef,
        public string $DL,
        public int $DLTypeRef,
        public string $Description,
        public string $Description_En,
        public string $FollowUpDate,
        public string $FollowUpNumber,
        public int $RowNumber,
        public string $SLCode,
        public string $ExtraData,
        public int $TaxAccountType,
        public int $TransactionType,
        public int $TaxStateType,
        public int $PurchaseOrSale,
        public int $ItemOrService,
        public int $PartyRef,
        public float $TaxAmount,
        public float $TollAmount,
        public string $SLTitle,
        public bool $IsSLTraceable,
        public int $OperationalCurrencyPrecision,
        public string $DLLevelTitle,
        public int $CurrencyPrecision,
        public string $CurrencyTitle,
        public int $BaseCurrencyPrecision,
        public string $BaseCurrencyTitle,
        public int $NumberOfSLDLLevels,
        public int $Quantity,
    ) {}

    /**
     * @return array{
     *           VoucherItemID: int,
     *           SLRef: int,
     *           Debit: float,
     *           Credit: float,
     *           CurrencyAmount: float,
     *           BaseCurrencyAmount: float,
     *           CurrencyCredit: float,
     *           CurrencyDebit: float,
     *           CurrencyRef: int,
     *           BaseCurrencyRef: int,
     *           OperationalCurrencyExchangeRate: float,
     *           OperationalCurrencyExchangeRateRef: int,
     *           BaseCurrencyExchangeRate: float,
     *           BaseCurrencyExchangeRateRef: int,
     *           DL: string,
     *           DLTypeRef: int,
     *           Description: string,
     *           Description_En: string,
     *           FollowUpDate: string,
     *           FollowUpNumber: string,
     *           RowNumber: int,
     *           SLCode: string,
     *           ExtraData: string,
     *           TaxAccountType: int,
     *           TransactionType: int,
     *           TaxStateType: int,
     *           PurchaseOrSale: int,
     *           ItemOrService: int,
     *           PartyRef: int,
     *           TaxAmount: float,
     *           TollAmount: float,
     *           SLTitle: string,
     *           IsSLTraceable: bool,
     *           OperationalCurrencyPrecision: int,
     *           DLLevelTitle: string,
     *           CurrencyPrecision: int,
     *           CurrencyTitle: string,
     *           BaseCurrencyPrecision: int,
     *           BaseCurrencyTitle: string,
     *           NumberOfSLDLLevels: int,
     *           Quantity: int,
     *       }
     */
    public function toArray(): array
    {
        return get_object_vars($this);
    }
}
